SandstormMedia:
  Plumber:
    calculations:
      methodCallsOnObject:
        label: 'No. of Method Calls'
        type: regexSum
        regex: '#==>(.*)::.*#'
        crossfilter:
          numberOfBars: 20
      objectCreations:
        label: 'No. of Object Creations'
        type: regexSum
        regex: '#==>(.*)::__construct#'
        crossfilter:
          numberOfBars: 20
      totalRuntime:
        label: 'Runtime (ms)'
        type: timerSum
        timerName: 'Profiling Run'
        crossfilter:
          numberOfBars: 20
      totalMemory:
        label: 'Memory (kb)'
        type: maxMemory
        crossfilter:
          numberOfBars: 20

      startTime:
        label: 'Date'
        type: startTime
        listDisplayFn: 'function(d) { var f = d3.time.format("%Y-%m-%d %H:%M:%S"); return f(d.startTime);};'
        crossfilter:
          chartInitializer: |
            var dateDim = profileCrossfilter.dimension(function(d) { return d3.time.day(d["startTime"]);});

            theChart = barChart()
              .dimension(dateDim)
              .numberOfBars(20)
              .graphWidth(600)
              .group(dateDim.group())
              .x(d3.time.scale()
                .domain([startTimeBounds.min, startTimeBounds.max])
                .rangeRound([0, 600]));
            charts.push(theChart);

            var timeDim = profileCrossfilter.dimension(function(d) { return d["startTime"].getHours() + d["startTime"].getMinutes() / 60; });

            theChart = barChart()
              .dimension(timeDim)
              .numberOfBars(20)
              .graphWidth(240)
              .group(timeDim.group(Math.floor))
              .x(d3.scale.linear()
                .domain([0, 24])
                .rangeRound([0, 240]));
            charts.push(theChart);